### PR TITLE
windows-applet: add custom titlebar button layout option

### LINKED ISSUE #640: Window properties forces titlebar buttons layout to "Left" if "Right (with menu)" is not selected in MATE Tweaks
#### Expected behaviour

When opening `mate-window-properties` for the titlebar buttons to not change.

#### Actual behaviour

When opening `mate-window-properties` if you have "Right" or "Left (with menu)" selected in MATE Tweak, it will override this setting and force the user to use "Left".

#### Steps to reproduce the behaviour

1) Open MATE Tweak, set the window control placement to "Right" or "Left (with menu)"
2) Open `mate-window-properties`
3) Observe that if you had selected "Right" you now have "Left" controls, and if you had selected "Left (with menu)" you now have just "Left"

This is due to https://github.com/mate-desktop/mate-control-center/blob/4ab076eeb591f4bd9385181e91c77f49f1bd36ed/capplets/windows/mate-window-properties.c#L59 which defines the following
```
#define MARCO_BUTTON_LAYOUT_RIGHT "menu:minimize,maximize,close"
#define MARCO_BUTTON_LAYOUT_LEFT "close,minimize,maximize:"
```
These effectively map to "Right (with menu)" and "Left" in MATE Tweak.

At startup `mate-window-properties` checks if the user has picked "Right (with menu)", if the user hasn't, then it forces the user to the layout "Left". Instead of respecting their decision of "Right" or "Left (with menu)".

https://github.com/mate-desktop/mate-control-center/blob/4ab076eeb591f4bd9385181e91c77f49f1bd36ed/capplets/windows/mate-window-properties.c#L395
```
    str = g_settings_get_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY);
    gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu),
                              g_strcmp0 (str, MARCO_BUTTON_LAYOUT_RIGHT) == 0 ? 0 : 1);
    g_free (str);
```

Either `mate-window-properties` should have the two extra menu items of MATE Tweak, so that it can map all four. Or it should perform a more intelligent check that counts the controls on either side of the `:` in the settings.

#### MATE general version

1.24.1 (not sure where to get this info from ?)

#### Package version

$ apt policy mate-tweak mate-control-center
mate-tweak:
  Installed: 21.04.3-0ubuntu1
  Candidate: 21.04.3-0ubuntu1
  Version table:
 *** 21.04.3-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
mate-control-center:
  Installed: 1.24.1-1
  Candidate: 1.24.2-0ubuntu1
  Version table:
     1.24.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
 *** 1.24.1-1 100
        100 /var/lib/dpkg/status

#### Linux Distribution

Ubuntu MATE Hirsute 21.04 daily build

#### Link to bugreport of your Distribution (requirement)

https://bugs.launchpad.net/ubuntu/+source/mate-control-center/+bug/1906535

### PR DESCRIPTION
**Pull request by mbkma**
Fixes #640 
**Updated:**
The possible values for titlebar buttons positions are now: Right (with menu), Left (with menu), Right, Left.
With this PR, if the user altered the value via dconf-editor or mate-tweak or in another way to a different value, mcc does not overwrite this setting.

Test:
change marco->general->button-layout in dconf to an arbitrary value.
With PR the gsettings value is respected (not overwritten) when opening the windows applet from mcc.

**Update 2:**
csd windows respect the titlebar button layout as well, (see https://github.com/mate-desktop/mate-control-center/pull/574)

### CODE REVIEW

File: capplets/windows/mate-window-properties.c [hunk 1]
```diff
@@ -203,17 +198,44 @@ double_click_titlebar_changed_callback (GtkWidget *optionmenu,
                          gtk_combo_box_get_active (GTK_COMBO_BOX (optionmenu)));
 }
 
+static void
+on_titlebar_button_layout_entry_activate (GtkWidget *entry,
+                                          void      *data)
+{
+    g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, gtk_entry_get_text(GTK_ENTRY(entry)));
```
Comment (zhuyaliang) [inline capplets/windows/mate-window-properties.c:205]: It is dangerous not to check what ```gtk_entry_get_text(GTK_ENTRY(entry)）```returns strings. If the user does not enter anything, or if the user enters the wrong content, this will cause ```marco``` to restart repeatedly.

Comment (zhuyaliang) [inline capplets/windows/mate-window-properties.c:205]: It is dangerous not to check what ```gtk_entry_get_text(GTK_ENTRY(entry)）```returns strings. If the user does not enter anything, or if the user enters the wrong content, this will cause ```marco``` to restart repeatedly.

**Comment by zhuyaliang** [comment]
@mbkma ```titlebar_button_layout_entry ``` should not be provided directly to users, because we are not sure what users will input. If this is a very necessary function, we should check whether the input is valid

**Comment by zhuyaliang** [comment]
@mbkma ```titlebar_button_layout_entry ``` should not be provided directly to users, because we are not sure what users will input. If this is a very necessary function, we should check whether the input is valid

**Comment by raveit65** [comment]
@ahayzen
Does this fix your problem with mat-tweak?

**Comment by raveit65** [comment]
Using left/right and left/right with menu is an great improvement and should fix mismatching settings with mate-tweak.
But i can't set any custom layout, eg. `menu:minimize,close`, which i can set easily with dconf-editor.
It seems there is no signal which sets the new value in the entry to dconf.
After closing/reopening the dialog the former value is back.

**Comment by mbkma** [comment]
@raveit65 you need to press enter in the TextEntryBox

**Comment by raveit65** [comment]
LOL, pressing enter in the GtkEntryBox helps a lot.
But i am sure that i will not be the only one who will run in this problem.
Maybe we can improve it and make it user friendly with a text under the box `press enter to apply changes` ?
Or another kind of help.
My first thought was to to close the dialog to apply changes.

**Comment by raveit65** [comment]
Ok, it is possible to add a bogus value, eg. `dirty:ugly,bad,angry`, which leads to windows without buttons and menu.
It's good that marco don't crash, but i agree wth @zhuyaliang that it shouldn't be possible to add a bogus value, .....if possible.

**Comment by ahayzen** [comment]
> @ahayzen
> Does this fix your problem with mate-tweak?

Looking at the code it looks like it should work, as it doesn't overwrite the options picked in MATE Tweak and is now able to detect them.

Eg the following options are now detected and respected
```
#define MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU "menu:minimize,maximize,close"
#define MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU "close,minimize,maximize:menu"
#define MARCO_BUTTON_LAYOUT_RIGHT ":minimize,maximize,close"
#define MARCO_BUTTON_LAYOUT_LEFT "close,minimize,maximize:"
```

**Comment by raveit65** [comment]
@mbkma 
Was there a change with latest forced push?

**Comment by raveit65** [comment]
This is much better without having a custom option in the gui. Advanced users can always use dconf-editor to use a special button order for their own risk.
Switching buttons in CSD windows works fine.

**Review by raveit65 — APPROVED** [review]
LGTM,
does what it promise.

**Comment by mbkma** [comment]
@raveit65 yes, for the changes see the updated PR description. Ok, next time i just post a new comment if I change something, to get you notified.

**Review by zhuyaliang — APPROVED** [review]

**Review by rbuj — CHANGES_REQUESTED** [review]
Use an enumeration instead of using integers (0 to 4).

**Comment by rbuj** [comment]
```diff
diff --git a/capplets/windows/mate-window-properties.c b/capplets/windows/mate-window-properties.c
index bffe66c..443a95b 100644
--- a/capplets/windows/mate-window-properties.c
+++ b/capplets/windows/mate-window-properties.c
@@ -59,10 +59,21 @@
 #define MARCO_COMPOSITING_MANAGER_KEY "compositing-manager"
 #define MARCO_COMPOSITING_FAST_ALT_TAB_KEY "compositing-fast-alt-tab"
 
-#define MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU "menu:minimize,maximize,close"
-#define MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU "close,minimize,maximize:menu"
-#define MARCO_BUTTON_LAYOUT_RIGHT ":minimize,maximize,close"
-#define MARCO_BUTTON_LAYOUT_LEFT "close,minimize,maximize:"
+enum
+{
+    MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU = 0,
+    MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU,
+    MARCO_BUTTON_LAYOUT_RIGHT,
+    MARCO_BUTTON_LAYOUT_LEFT,
+    MARCO_BUTTON_LAYOUT_COUNT
+};
+
+static const char *button_layout [MARCO_BUTTON_LAYOUT_COUNT] = {
+   [MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU] = "menu:minimize,maximize,close",
+   [MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU]  = "close,minimize,maximize:menu",
+   [MARCO_BUTTON_LAYOUT_RIGHT]           = ":minimize,maximize,close",
+   [MARCO_BUTTON_LAYOUT_LEFT]            = "close,minimize,maximize:"
+};
 
 /* keep following enums in sync with marco */
 enum
@@ -208,47 +219,36 @@ titlebar_layout_changed_callback (GtkWidget *optionmenu)
 {
     gint value = gtk_combo_box_get_active (GTK_COMBO_BOX (optionmenu));
 
-    if (value == 0) {
-        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU);
-        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU);
-    }
-    else if (value == 1) {
-        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU);
-        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU);
+    if (value < MARCO_BUTTON_LAYOUT_COUNT) {
+        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, button_layout[value]);
+        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, button_layout[value]);
     }
-    else if (value == 2) {
-        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_RIGHT);
-        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_RIGHT);
-    }
-    else if (value == 3) {
-        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_LEFT);
-        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, MARCO_BUTTON_LAYOUT_LEFT);
-    }
-    else if (value == 4) { /* Custom Layout */
-        if (custom_titlebar_button_layout)
-        {
-            g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, custom_titlebar_button_layout);
-            g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, custom_titlebar_button_layout);
-        }
+    /* Custom Layout */
+    else if ((value == MARCO_BUTTON_LAYOUT_COUNT) && (custom_titlebar_button_layout)) {
+        g_settings_set_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY, custom_titlebar_button_layout);
+        g_settings_set_string (interface_settings, GTK_BUTTON_LAYOUT_KEY, custom_titlebar_button_layout);
     }
 }
 
 static void
 set_titlebar_button_layout(void)
 {
-    gchar *str = g_settings_get_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY);
-
-    if (g_strcmp0 (str, MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU) == 0)
-        gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), 0);
-    else if (g_strcmp0 (str, MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU) == 0)
-        gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), 1);
-    else if (g_strcmp0 (str, MARCO_BUTTON_LAYOUT_RIGHT) == 0)
-        gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), 2);
-    else if (g_strcmp0 (str, MARCO_BUTTON_LAYOUT_LEFT) == 0)
-        gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), 3);
-    else /* A custom value is found in MARCO_BUTTON_LAYOUT_KEY
-          * (maybe the user changed the value in dconf-editor) */
-    {
+    gchar    *str;
+    gint      i;
+    gboolean  found = FALSE;
+
+    str = g_settings_get_string (marco_settings, MARCO_BUTTON_LAYOUT_KEY);
+    for (i = 0; i < MARCO_BUTTON_LAYOUT_COUNT; i++) {
+        if (g_strcmp0 (str, button_layout[i])) {
+            gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), i);
+            found = TRUE;
+            break;
+        }
+    }
+    /* A custom value is found in MARCO_BUTTON_LAYOUT_KEY
+     * (maybe the user changed the value in dconf-editor) */
+    if (!found) {
+        g_free (custom_titlebar_button_layout);
         custom_titlebar_button_layout = g_strdup(str);
         gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (titlebar_layout_optionmenu), _("Custom"));
         gtk_combo_box_set_active (GTK_COMBO_BOX (titlebar_layout_optionmenu), 4);
```

**Comment by mbkma** [comment]
@rbuj nice code, I will update this PR soon

**Review by rbuj — APPROVED** [review]

**Comment by rbuj** [comment]
> @rbuj nice code, I will update this PR soon

ok, don't worry

**Comment by mbkma** [comment]
done :)

**Review by raveit65 — APPROVED** [review]
I tested it again,
... works like a charm.
